name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      working-directory: health-calculator-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      working-directory: health-calculator-service
      run: |
        pytest tests/

    - name: Build Docker Image
      working-directory: health-calculator-service
      run: |
        docker build -t etumchihi92/health-calculator-service:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image to Docker Hub
      working-directory: health-calculator-service
      run: |
        docker push etumchihi92/health-calculator-service:latest

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'health-calculator-apppythoncourse'
        images: 'etumchihi92/health-calculator-service:latest'